### ISSUE TITLE
Bioconda package

### ISSUE THREAD

**Issue by unode** [motu-tool/mOTUs_v2#13]
Submitted [here](https://github.com/bioconda/bioconda-recipes/pull/9239) and waiting for 2.0.0 release to be concluded.

**Comment by AlessioMilanese** [comment]
Version 2.0.0 is now on bioconda.
I see that it is available only for linux, but it should work for macOS as well, right?!

**Comment by hjruscheweyh** [comment]
Just talked to one of the bioconda people. The reason is that "skip: True # [osx]" is set in the meta.yaml file. Whats the reason?

He also said that the meta.yaml should contain a maintainer field so that its clear who submitted this package.

**Comment by AlessioMilanese** [comment]
@unode, can you change the "skip: True # [osx]" so that we can install it also on macOS?

**Comment by unode** [comment]
I won't be able to test this myself, since I don't use OSX.
Regardless see https://github.com/bioconda/bioconda-recipes/pull/10125

**Comment by unode** [comment]
Merged, could any of you running on OSX test it once it comes out?

**Comment by AlessioMilanese** [comment]
Still doesn't work:
```
>conda install -c bioconda motus
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - motus

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
```
I also don't see the icon of OSX in bioconda:
<img width="686" alt="screen shot 2018-08-25 at 19 07 13" src="https://user-images.githubusercontent.com/16308111/44620748-27258380-a89a-11e8-9e39-18ffd0851fed.png">

maybe we have to wait that it update?!

**Comment by unode** [comment]
It seems `py27_1` is all we'll get.
Since it's now packaged as `noarch` (includes MS Windows - possibly unintended).

Can you check if you can install it on any python environment or if it's restricted to Python 2.7?
If it's 2.7 only this is a bug in the bioconda infrastructure.

**Comment by AlessioMilanese** [comment]
I have ```anaconda 4.2.0``` with ```python 3.5.2``` and it installed correctly.
