### ISSUE TITLE
All_2481_at_least_500.motu.nr.out.20180307.tsv - the names of mOTU version2 references not found

### ISSUE THREAD

**Issue by Jigyasa3** [motu-tool/mOTUs_v2#20]
I can't find the file "All_2481_at_least_500.motu.nr.out.20180307.tsv", which was available before, to annotate the mOTU version 2 references?

**Comment by AlessioMilanese** [comment]
You can find it in:
https://motu-tool.org/download.html

It's the first line.

I'm copying the ftp link also here:
https://motu-tool.org/data/All_2481_at_least_500.motu.nr.out.20180307.tsv

**Comment by Jigyasa3** [comment]
I am sorry to keep disturbing you. But I have checked the All_2481_at_least_500.motu.nr.out.20180307.tsv file and all the accessory files associated with mOTU.v2. But none of them have the "name" of the metagenome from which the markers were extracted from.
For example-
metaMG0001672  only has the bacteria "unknown Faecalibacterium" associated with it. Not the metagenome from which Faecalibacterium was sequenced from.

Is the information about the metagenome name kept in the annotation file?

**Comment by AlessioMilanese** [comment]
You can find this information in [this file](https://www.embl.de/download/zeller/metaMGs_2_sample.tsv.zip) (first column is the gene id and second column is the sample+scaffold information). The samples map to the [Supplementary Data 1](https://www.nature.com/articles/s41467-019-08844-4#Sec30) file of the mOTUs2 paper. Note that you might have to parse the information that you are interested in. For example in the attached file you have:
```
metaMG0000000.COG0012	MH0350_revised_scaffold61325_1
metaMG0000001.COG0012	V1.FI14_revised_scaffold25112_1
```
For the first gene, you can find in [Supplementary Data 1](https://www.nature.com/articles/s41467-019-08844-4#Sec30) at line 1507 the sample:
```
MH0350 | 2 | ST | ERR414298,ERR414579 | 1
```
