### ISSUE TITLE
profiling contigs over reads?

### ISSUE THREAD

**Issue by raw937** [motu-tool/mOTUs_v2#22]
Hello, 

Is it possible to profile contigs over reads?

**Comment by AlessioMilanese** [comment]
Hi @raw937,

Not really. We are mapping reads using bwa, which is designed for short reads.
Check out:
https://github.com/AlessioMilanese/classify-genomes

Do you have contigs or metagenome-assembled genomes?

**Comment by raw937** [comment]
Thanks for this!

I have good genome bins. This very helpful. 
I am trying to find a way to convert the long contigs (>5k) into mOTUs that aren't binning well.

**Comment by raw937** [comment]
This is a cool tool "classify-genomes." I can't get the databases to download.
 python setup.py 
 ------------------------------------------------------------------------------
|                           SETUP CLASSIFY-GENOMES                             |
 ------------------------------------------------------------------------------
Download the compressed motus database (~1Gb)
 954997496  [100.00%]

Check md5: MD5 verified
Extract files from the archive...Error: failed to extract files

I tried to copy from mOTU_v2 no success.

**Comment by AlessioMilanese** [comment]
Looking at 
https://github.com/AlessioMilanese/classify-genomes/issues/1

it's because you exceed your disk quota. You would need ~1Gb of free space.

**Comment by AlessioMilanese** [comment]
Issue solved in https://github.com/AlessioMilanese/classify-genomes/issues/1
