### ISSUE TITLE
Question: What does -1 represent in output?

### ISSUE THREAD

**Issue by sturne29** [motu-tool/mOTUs_v2#23]
I haven't been able to find this anywhere. What does -1 mean in the "consensus_taxonomy" column mean?

**Comment by AlessioMilanese** [comment]
The -1 at the end of the profile represents the fraction of unmapped reads (species that exists, but we cannot measure).
If you look at [Figure 1a](https://www.nature.com/articles/s41467-019-08844-4/figures/1) of the mOTUs2 paper, the -1 would represent the reads that maps to the cluster in MG2 that is not linked.

**Comment by AlessioMilanese** [comment]
Hi @sturne29,

I improved the wiki, adding more information. See
https://github.com/motu-tool/mOTUs_v2/wiki/Explain-the-resulting-profile
