### ISSUE TITLE
Typo in the wiki

### ISSUE THREAD

**Issue by fbeghini** [motu-tool/mOTUs_v2#24]
Hi Alessio,
just wanted to point out that I've found a typo in this [wiki's page](https://github.com/motu-tool/mOTUs_v2/wiki/Parameters-to-change-the-resulting-profiles).

In the CAMI format section, the last command, the -C parameter should be `-C recall` and not `-C parenthesis`

Best,
Francesco

**Comment by AlessioMilanese** [comment]
Good catch Francesco,

I corrected it now,
Thanks,
alessio
