### ISSUE TITLE
error when extending database with incomplete genome

### ISSUE THREAD

**Issue by aistBMRG** [motu-tool/mOTUs_v2#25]
Thank you for developing this tools -- works well in our hands too.

Now, I am following your provided workflow for extending the database. However, it seems that the script throws on error when running with genomes containing not all 40 marker genes. More specifically, the vsearch step fails due to missing input file. This seems somewhat unexpected.

Would it be possible to clarify how to avoid such issue.

Thanks.

Dieter

**Comment by hjruscheweyh** [comment]
Hi Dieter,

thanks for using the tool and the extender. Can you please send the exact command you used and the  file with the stdout log of the extender? Are you trying to add a public genome? Then please also add the link to this genome.

Thanks a lot,
Hans

**Comment by aistBMRG** [comment]
Hi Hans,

Thank you for the prompt reply.

I am running the "extend_mOTUs_addGenome.sh" script with a custom genome that I know contains seven out of 10 marker genes used for metagenome profiling. 

It seems that the error, expectedly, occurs at the following step:

mkdir -p $new_database_folder/dbs/$genome_ID/vsearch
while read line; do
vsearch --threads 38 --usearch_global $new_database_folder/dbs/${genome_ID}/${genome_ID}_markerGenes2/**$line.notab.fna** --db ${unpadded_mOTUseqsFile}.udb --id 0.8  --maxaccepts 100000 --mincols 20 --blast6out $new_database_folder/dbs/$genome_ID/vsearch/$line.distances_vs_db.m8
done < **$mOTU_MG_file** # note I updated the number of threads #

As far as I understand, the command will be applied to all genes in _$mOTU_MG_file_, which is the default and contains 10 marker gene COG identifiers. What happens is that for some genes the _$line.notab.fna_ file is empty and so vsearch fails to locate that file. I guess I could modify the bash script to generate a list of genes that were found and then loop through these only ...

Regards,

Dieter.

**Comment by hjruscheweyh** [comment]
HI Dieter

Thanks for the Feedback. We will have a look into this issue and come back to you once we have a fix. Best,
Hans

**Comment by hjruscheweyh** [comment]
Hi Dieter

We have updated the extender software to work with the new database structure introduced in version 2.5. We believe that we also fixed your bug. Let me know if the issue persists.

hans

**Comment by hjruscheweyh** [comment]
Closing this issue. Let me know if you continue having issues.
