### ISSUE TITLE
Support for Pavian

### ISSUE THREAD

**Issue by Anto007** [motu-tool/mOTUs_v2#27]
Hi,

mOTUS_v2 is cool! I like it more than the previous version. Is there any way that you could provide an additional script to make the profiling output compatible with visualization on Pavian (https://fbreitwieser.shinyapps.io/pavian/)? Many thanks!

**Comment by AlessioMilanese** [comment]
Hi @Anto007,
Thanks for using mOTUs!
I think I got a similar request, see issue https://github.com/motu-tool/mOTUs_v2/issues/21.

We can add the feature to the next release!

Cheers,
alessio

**Comment by Anto007** [comment]
Many thanks! Also, why retain taxa with zero relative abundance in the final output file? In my opinion, a cleaner output file will be a one which has got only taxa that were detected (>0 abundance)

**Comment by AlessioMilanese** [comment]
In that format there will be only the ones different from zero.
Check also the [-C option](https://github.com/motu-tool/mOTUs_v2/wiki/Parameters-to-change-the-resulting-profiles#cami-bioboxes-format--c)

**Comment by AlessioMilanese** [comment]
Hi @Anto007,
I implemented a new feature to print the result that should be supported by Pavian.
For now it's available only on GitHub (you need to pull the latest version), but we will soon tag a new version that will be available also on conda.

You can call the `profile` command with the option `-A` . For now it is commented only within the code, I will add more information to the wiki when we tag the new version.

Example, with a call:
```
motus profile -s test1_single.fastq -o res1.motus -n test1 -A 
```
You have:
```
clade	test1
k__Bacteria	1.0000000000
k__Bacteria|p__Proteobacteria	0.0732714431
k__Bacteria|p__Firmicutes	0.6479060231
k__Bacteria|p__Thermodesulfobacteria	0.0055578606
k__Bacteria|p__Actinobacteria	0.2200557062
k__Bacteria|p__Chlamydiae	0.0532089670
k__Bacteria|p__Proteobacteria|c__Gammaproteobacteria	0.0557659685
k__Bacteria|p__Proteobacteria|c__Alphaproteobacteria	0.0175054746
k__Bacteria|p__Firmicutes|c__Erysipelotrichia	0.0688211617
k__Bacteria|p__Firmicutes|c__Negativicutes	0.0234955832
k__Bacteria|p__Firmicutes|c__Bacilli	0.4538976397
k__Bacteria|p__Firmicutes|c__unknown Firmicutes	0.1016916385
...
k__Bacteria|p__Actinobacteria|c__Actinobacteria|o__Corynebacteriales|f__Corynebacteriaceae|g__Corynebacterium|s__Corynebacterium sp. GD7 [ref_mOTU_v2_2683]	0.0390911725
k__Bacteria|p__Proteobacteria|c__Gammaproteobacteria|o__Vibrionales|f__Vibrionaceae|g__Vibrio|s__Vibrio tubiashii [ref_mOTU_v2_3913]	0.0044390411
k__Bacteria|p__Actinobacteria|c__Actinobacteria|o__Streptomycetales|f__Streptomycetaceae|g__Streptomyces|s__Streptomyces durhamensis [ref_mOTU_v2_4783]	0.0725347907

```

**Comment by Anto007** [comment]
Many thanks but did you happen to try res1.motus on Pavian? I think the format is still unsuitable. I ran your exact new command-line and tried out the test output file at https://fbreitwieser.shinyapps.io/pavian/ and I got this error message: "The following files did not conform the report format:
- mOTUs_test_taxonomic_profile.report"

**Comment by Anto007** [comment]
Wonder if this has anything to do with your -A output not appearing in sorted descending order in terms of relative abundance for all taxonomic ranks. For example, shouldn't "k__Bacteria|p__Firmicutes	0.6479060231" appear at the very top of the p__ (phylum) taxonomic rank followed by "k__Bacteria|p__Actinobacteria	0.2200557062"?

**Comment by Anto007** [comment]
Here's a sample metaphlan2 output file that worked on Pavian
[Corr_clean_phiclean_10_8_profiled_metagenome.txt](https://github.com/motu-tool/mOTUs_v2/files/3389620/Corr_clean_phiclean_10_8_profiled_metagenome.txt)

**Comment by AlessioMilanese** [comment]
Hi @Anto007,
The problem is that Pavian expects this header:
```
#SampleID	Metaphlan2_Analysis
```

If you change the motus result from:
```
clade	test1
k__Bacteria	1.0000000000
k__Bacteria|p__Proteobacteria	0.0732714431
k__Bacteria|p__Firmicutes	0.6479060231
...
```
to:
```
#SampleID	Metaphlan2_Analysis
k__Bacteria	1.0000000000
k__Bacteria|p__Proteobacteria	0.0732714431
k__Bacteria|p__Firmicutes	0.6479060231
```
Then it will work.

I wrote to the developer of Pavian to see if it wold be possible to add mOTUs 2, see: https://github.com/fbreitwieser/pavian/issues/58

Note1: mOTUs results are relative abundances that sum up to 1, while for metaphlan they sum up to 100.
Note2: I changed just now the header to `#mOTUs2_clade	sample_name`

**Comment by Anto007** [comment]
Works nicely when the output file's header is changed to metaphlan2-style. Thank you so much!
