### ISSUE TITLE
Mouse metagenomic DB

### ISSUE THREAD

**Issue by kunstner** [motu-tool/mOTUs_v2#28]
Hi,

I'm testing mOTUs2 with some mouse metagenomic data (cecum content). Do you have any plans to augment the existing database by other organisms (e.g. mouse) as well? The existing database works fine with my samples but I'm wondering whether I can increase the specificity when using a more mouse specific database.

Thanks,
 Axel

**Comment by AlessioMilanese** [comment]
Hi @kunstner,

Thanks for using mOTUs!
We didn't have time to test now in mouse, it would be interesting to know how many meta-mOTUs you can profile there.

> Do you have any plans to augment the existing database by other organisms (e.g. mouse) as well?

We are not working on it at the moment, but we are planning to add more biomes (like mouse, pig and dog gut, as well as environmental biomes as soil and fresh water).
I cannot give you a date now, but I can keep you updated.
For now, you can use some scripts to add MAGs (that you might reconstruct from your samples) to the mOTUs profile and be able to profile them correctly (see https://motu-tool.org/installation.html)

Best,
alessio

**Comment by kunstner** [comment]
Hi @AlessioMilanese,

thanks a lot for the quick reply!

The proportion of unmapped reads is betwenn 1 and 30% (with two outliers ~55%). I think this is rather good and at least better than kraken.

Indeed, we are planning to assemble the data as well. 

Looking forward to see an updated database at some point.

Best,
 Axel

**Comment by hh1985** [comment]
We have metagenomics datasets from patients. Is there any way to update the meta-mOTUs ?

**Comment by AlessioMilanese** [comment]
Hi @hh1985,

there are no automatic scripts to update the mOTUs database. The procedure had many manual steps and internal checks (which are described in the [mOTUs paper, online methods](https://www.nature.com/articles/s41467-019-08844-4)), which are not easy to automate.

What data do you have? If it is stool samples, I think that the meta-mOTUs can cover the vast majority of your species. For example, from two big MAGs projects: [Pasolli et al. Cell 2019](https://www.sciencedirect.com/science/article/pii/S0092867419300017) and [Almeida et al. Nature 2019](https://www.nature.com/articles/s41586-019-0965-1) we cover 96.4% and 97.9% respectively of all the MAGs with our mOTUs. Note that *Pasolli et al.* reconstruct MAGs from Human associated biomes from more than 9,000 metagenomes, so even for other human body sites we have a good coverage.

As another note, I don't know if your patients have any particular disease, but we constructed the meta-mOTUs from metagenomes with medical relevance:

- Feng, Q. et al. Gut microbiome development along the colorectal adenoma-carcinoma sequence. Nat. Commun. 6, 6528 (2015).

- Karlsson, F. H. et al. Gut metagenome in European women with normal, impaired and diabetic glucose control. Nature 498, 99–103 (2013).

- Qin, J. et al. A human gut microbial gene catalogue established by metagenomic sequencing. Nature 464, 59–65 (2010).

- Qin, J. et al. A metagenome-wide association study of gut microbiota in type 2 diabetes. Nature 490, 55–60 (2012).

- Voigt, A. Y. et al. Temporal and technical variability of human gut metagenomes. Genome Biol. 16, 73 (2015).

- Zeller, G. et al. Potential of fecal microbiota for early-stage detection of colorectal cancer. Mol. Syst. Biol. 10, 766 (2014).

**Comment by hh1985** [comment]
It sounds like updating meta-mOTUs is itself a project!

The data we have are from stool samples of cancer patients (not only CRC, but many other types of cancers).  We can check the coverage to see how mOTUs2 work on our dataset.

Thanks!

**Comment by AlessioMilanese** [comment]
I'm closing the issue and I will write some updates when we have them.
