### ISSUE TITLE
Surprising results - No unmapped reads

### ISSUE THREAD

**Issue by sturne29** [motu-tool/mOTUs_v2#30]
Not a bug or an issue as such, but I wanted some input on some results I got recently. I was using the tool with all default settings to profile several freshwater aquatic samples (sediment and water). One of my sediment samples had no unmapped reads, which is surprising because:

- It was a biological replicate and the other replicates from the same sampling time and condition did have unmapped reads. As far as I can tell, nothing about how I processed that sample as compared to the others should have resulted in such a stark difference
- I would expect aquatic sediments in general to have a relatively substantial fraction of unmapped reads because of the lack of references. This is the case for the other replicates from that time and condition

This, along with the fact that very few phyla were identified for those samples (I would expect sediment communities to be fairly diverse and to have members from several different known phyla) makes me wonder if I should be using different settings, or if something could be going wrong during the profiling?

Thank you for any input you might have.

**Comment by AlessioMilanese** [comment]
Hi @sturne29 ,

I'm happy to hear that you are interested in using mOTUs2. We didn't create mOTUs specifically for fresh water, so some species might be missing. If you want to play with the parameters, I would suggest you to read [here](https://github.com/motu-tool/mOTUs_v2/wiki/Increase-precision-or-recall).

But, my guess is that this "problematic" sample has few reads and hence few are mapping to the marker genes that we are using for profiling. If this is the case, I think you will have to remove the sample from your analysis.

If you want, you can try to send me two profiles (the problematic one and the good biological replica and I can have a look).

Cheers,
alessio

**Comment by sturne29** [comment]
Thank you for the insight! I may try some different settings, but I might need to try something else. I really appreciate the ease of use and clarity of output from this tool, and if there's ever an update that includes more freshwater or other environmental habitats I'd love to give it another shot.

The sample itself seems to be about the same quality as my other samples after QC and trimming/low-quality read removal, so I'm not sure that that's the issue.

Thank you for taking the time to help me, both now and earlier!
