### ISSUE TITLE
Is it possible to use fasta files instead of fastq files and get the number of marker genes assigned to it?

### ISSUE THREAD

**Issue by Jigyasa3** [motu-tool/mOTUs_v2#33]
Hey @AlessioMilanese 

I wanted to ask if its possible to do the following-
a) Use fasta files (contigs/MAGs) rather than fastq files to get the relative abundance information?
b) The final output is relative abundance information of bacterial taxa, is it also possible to get the number of marker genes associated with the bacterial taxa. 

For example,
Current output-
**Taxonomy                Relative abundance**
Proteobacteria	0.0732714431
Firmicutes	0.6479060231
Nitrospinae	0.0000000000

Custom output-
**Taxonomy                Relative abundance   Number_of_marker_genes**
Proteobacteria	0.0732714431   5
Firmicutes	0.6479060231    4
Nitrospinae	0.0000000000   10

**Comment by AlessioMilanese** [comment]
Hi @Jigyasa3,

a) you would like to add a MAG to the database and be able to profile it? In this case, you can check the augmentation script at https://motu-tool.org/ under INSTALLATION.

**Comment by AlessioMilanese** [comment]
b) you need to use the `-M` option to save the read count per marker gene cluster (MGC), there are maximum 10 MGC per mOTU. Additionally, from the mOTUs database (https://zenodo.org/record/3366460) you need:
1. `db_mOTU_MAP_MGCs_to_mOTUs.tsv` to map the MGCs produced by `-M` to the mOTUs,
2. `db_mOTU_taxonomy_ref-mOTUs.tsv` and `db_mOTU_taxonomy_meta-mOTUs.tsv` to have the taxonomy annotation of the mOTUs.

**Comment by Jigyasa3** [comment]
Hey @AlessioMilanese 
Thank you for replying.
As for a), I checked the extend_mOTUs_DB scripts. That's not what I am looking for. I was wondering if its possible to use the original script on fasta files rather than fastq files. I want to find the taxonomy of metagenome bins using marker genes. The bins are in fasta format, already extracted from the reads and scaffolds (using CONCOCT software).

As for b), I will check that. Thanks again for replying!

**Comment by AlessioMilanese** [comment]
> I was wondering if its possible to use the original script on fasta files rather than fastq files. I want to find the taxonomy of metagenome bins using marker genes.

For this you can use:
https://github.com/AlessioMilanese/classify-genomes

**Comment by Jigyasa3** [comment]
Thank you! That's exactly what I was looking for.
