### ISSUE TITLE
Phylogeny of the mOTUs?

### ISSUE THREAD

**Issue by mikemc** [motu-tool/mOTUs_v2#35]
Is a phylogeny with all of the mOTUs available? I read that one was created for the mOTUs2 paper, but didn't see it online or in the repository. If not, then I'll suggest providing a phylogeny for the current set of mOTUs as a very useful enhancement!

**Comment by AlessioMilanese** [comment]
Hi @mikemc,

Thanks for your interest in mOTUs.
A phylogenetic tree for mOTUs version 2.0.0 is already available at motu-tool.org under DATA.
We will provide a new phylogeny for the new set of mOTUs soon.

**Comment by fconstancias** [comment]
any updates related the phylogenetic tree?
thanks

**Comment by AlessioMilanese** [comment]
Hi @fconstancias & @mikemc,

Actually yes. See attached: [mOTUS_2.5.treefile.zip](https://github.com/motu-tool/mOTUs_v2/files/4656038/mOTUS_2.5.treefile.zip)

**Comment by hjruscheweyh** [comment]
Also added the file to the motu-tool.org website in the data section

**Comment by agavriilidou** [comment]
Hi @AlessioMilanese,
Do you have a tree file also for mOTUs_3.1 ?

Thanks!
AG
