### ISSUE TITLE
What does mean the last row of output ?

### ISSUE THREAD

**Issue by ryo-aoki3** [motu-tool/mOTUs_v2#36]
Hi.

I run motu profile and got the output file.
The last row of output files had no taxonomic information as described below 
What does it mean ?

When the value of the last row was omitted, sum of the abundance was less than 1.
How shold I treat thes values ?
```
unknown Opitutae [meta_mOTU_v2_7797]	0.0000000000
unknown Roseburia [meta_mOTU_v2_7798]	0.0000000000
unknown Firmicutes [meta_mOTU_v2_7799]	0.0000000000
unknown Clostridiales [meta_mOTU_v2_7800]	0.0000000000
-1	0.0134381884
```

**Comment by AlessioMilanese** [comment]
Hi @ryo-aoki3,
Thanks for your interest in mOTUs.
Check:
https://github.com/motu-tool/mOTUs_v2/wiki/Explain-the-resulting-profile
In particular the last paragraph will explain the -1.
