### ISSUE TITLE
Quick question regarding identification of eukaryotes

### ISSUE THREAD

**Issue by Anto007** [motu-tool/mOTUs_v2#37]
If my understanding is correct, mOTUs2 only detects prokaryotes and not any of the eukaryotes; right?

**Comment by AlessioMilanese** [comment]
That's correct (bacteria and archaea).

**Comment by Anto007** [comment]
Many thanks for your super-quick response as always!

**Comment by AlessioMilanese** [comment]
no problem. I'm closing it.
Cheers,
alessio
