### ISSUE TITLE
Classify Nanopore reads?

### ISSUE THREAD

**Issue by angelovangel** [motu-tool/mOTUs_v2#38]
Hi,
what do you think about using mOTUs2 for profiling Nanopore reads?

**Comment by AlessioMilanese** [comment]
Hi Angel,
I'm happy to hear that you are interested in using mOTUs2.
We are using bwa to map (short) reads to the mOTUs marker gene database (sequences of ~2,000 nucleotides).
With long reads (as in the case of Nanopore), this method would not work. I think a better approach would be to extract the marker genes from the reads and map them to the mOTUs marker genes (see https://github.com/AlessioMilanese/classify-genomes).

Another thing to consider is that using nanopore reads you will have few reads (compare to illumina), and maybe it's not the best approach for profiling (i.e. quantifying species abundances).
