### ISSUE TITLE
Problem with the Map_snv wiki page 

### ISSUE THREAD

**Issue by mikemc** [motu-tool/mOTUs_v2#43]
Currently the [Map_snv wiki page](https://github.com/motu-tool/mOTUs_v2/wiki/Map_snv) is mostly a direct copy of the [Map_tax](https://github.com/motu-tool/mOTUs_v2/wiki/Map_tax) wiki page, and all of the commands it shows use `motus map_tax` instead of `motus map_snv`.

**Comment by AlessioMilanese** [comment]
Good catch. Corrected it now.
Cheers,
alessio
