### ISSUE TITLE
Problem when adding my own genomes to the reference db

### ISSUE THREAD

**Issue by lsayaved** [motu-tool/mOTUs_v2#44]
Hi Alessio,
I am trying to add my own genomes to the database, but I can't run the script extend_mOTUs_addGenome.sh successfully because the file mOTU.v2b.nr.padded.udb is missing from the db folder. Thanks for your help!
Lizbeth

**Comment by hjruscheweyh** [comment]
Hi Lizbeth

There are still some inconsistencies between database v2.1.x. and v2.5.x. My guess is that you're using v2.5.x

I will try to fix this next week and will release an `v2.1.x_extender` and an `2.5.x_extender`.

Hans

**Comment by hjruscheweyh** [comment]
Hi Lizbeth

We still have some issues regarding the new version of the extender. I will try to fix it as soon as a I can and will let you know once we have a workable solution.

Hans

**Comment by hjruscheweyh** [comment]
Hi Lizbeth

We finished the coding and will perform some final testing. I will keep you posted.
Hans

**Comment by hjruscheweyh** [comment]
Hi Lizbeth

The extender for the v2.5 was released today. Please check if this solves your issues.

Hans

**Comment by hjruscheweyh** [comment]
Closing this issue. Let me know if you continue having issues.

**Comment by Jibowe** [comment]
Hi，
I am using extend_mOTUs_DBv2.5 and mOTUs v3.0.1. And I had the same problem. I can't run the script extend_mOTUs_addGenome.sh successfully because the file db_mOTU_DB_NR.fasta.udb was not found in the db folder.
Thanks for your help!
