### ISSUE TITLE
Can not download db_mOTU_v2.5.1.tar.gz

### ISSUE THREAD

**Issue by PandengWang** [motu-tool/mOTUs_v2#46]
Hi, @AlessioMilanese 
Thanks for this useful tool!
I can not download the database from https://zenodo.org/record/3366460/files/db_mOTU_v2.5.1.tar.gz, when I tried to install motus.

Could you provide another web link, such as figshare, to download this database?

Thanks.
Pandeng

**Comment by AlessioMilanese** [comment]
Hi Pandeng,
Thanks for using the tool and reporting the issue.

>I can not download the database from https://zenodo.org/record/3366460/files/db_mOTU_v2.5.1.tar.gz, when I tried to install motus.

Can you copy here the error that you got when running `python setup.py`?

>Could you provide another web link, such as figshare, to download this database?

I would prefer to solve the issue with Zenodo. First, because it's embedded in the `setup.py` script and second, because if we put it on figshare, then we have to keep also that update.

**Comment by PandengWang** [comment]
Thanks so much for your quickly reply.
It didn't throw an error, but after downloading a few kb, the download speed began to drop to 0 kb/s.
I tried to download this database using  "Internet Download Manager" software and it also didn't work.
I'm in China. I'm doubting whether the download request will be automatically blocked by this website.
So, I would appreciate very much if you could provide me this database by other means.

Thanks.
Pandeng

**Comment by AlessioMilanese** [comment]
I added it to a ftp server.
Can you please change `setup.py` at line 15, from:
```
link_db = "https://zenodo.org/record/3366460/files/db_mOTU_v2.5.1.tar.gz"
```
to:
```
link_db = "https://www.embl.de/download/zeller/milanese/mOTUs2.5.1/db_mOTU_v2.5.1_test.tar.gz"
```

**Comment by PandengWang** [comment]
> I added it to a ftp server.
> Can you please change `setup.py` at line 15, from:
> 
> ```
> link_db = "https://zenodo.org/record/3366460/files/db_mOTU_v2.5.1.tar.gz"
> ```
> 
> to:
> 
> ```
> link_db = "https://www.embl.de/download/zeller/milanese/mOTUs2.5.1/db_mOTU_v2.5.1_test.tar.gz"
> ```
Problem is resolved.
Thanks so much!
