### ISSUE TITLE
motus profile can't output the bam file [Issue with samtools 1.10]

### ISSUE THREAD

**Issue by Shinexy99** [motu-tool/mOTUs_v2#52]
I have tested the code by execute as :
motus profile -s test1_single.fastq -o xx -I xx.bam -t 11
no right bam file out put.
it reported the error as :
[E::sam_hrecs_error] Missing tab at line 2: "@CO min_len_alignment 75"
samtools view: failed to add PG line to the header
[W::map_db] Warning: failed to save intermediate bam file
 [W::map_db] Warning: failed to save intermediate bam file

**Comment by AlessioMilanese** [comment]
Hi @Shinexy99,

Works all good for me, call:
```
motus profile -s db_mOTU_test/test1_single.fastq -o ~/Desktop/xx -I ~/Desktop/xx.bam
```
Print:
```
[main]  MAP_TAX -----------
[main] Number of detected lanes: 1
[main] Run bwa on lane 1
 [map_db](map single reads) 6.04 sec
[main] (Save bam file produced by bwa) 1.47 sec
[main] Total time map_tax: 7.65 sec
[main]  CALC_MGC -----------
[main] Minimum alignment length: 75 (average read length: 165)
 [calc_mgc](parse 1 sam/bam file) 3.48 sec
 [calc_mgc](get mgc abundances) 0.01 sec
[main] Total time calc_mgc: 3.75 sec
[main]  CALC_MOTU -----------
 [calc_motu] (Create taxonomy profile) 0.49 sec
[main]  TOTAL TIME (map_tax+calc_mgc+calc_motu): 11.89 sec
```

**Comment by AlessioMilanese** [comment]
Can I ask you to run:
```
samtools --version
```

and:
```
motus profile --test
```

**Comment by Shinexy99** [comment]
This is the result when running the test of motus profile --test
 ------------------------------------------------------------------------------
|                               TEST MOTUS TOOL                                |
 ------------------------------------------------------------------------------

1-- ran setup.py: done

2-- Tools and versions:
- python:    correct
- bwa:       correct
- samtools:  correct
- metaSNV:   WARNING. metaSNV is not in the path


3-- Taxonomy profiling test:
- Run motus (-v 1, only error messages):
- end motus call

Check resulting profile: correct

**Comment by Shinexy99** [comment]
my samtools version details:
samtools 1.10
Using htslib 1.10
Copyright (C) 2019 Genome Research Ltd.

**Comment by AlessioMilanese** [comment]
There is an issue with the header of the BAM file:
```
@PG	ID:bwa	PN:map_tax 2.5.1 | gene database: nr2.5.1 | 165
@CO min_len_alignment 75
@CO min_perc_id 97
@CO min_perc_query 45
@SQ	SN:metaMG0000000.COG0012	LN:1694
@SQ	SN:metaMG0000001.COG0012	LN:1646
```

After `@PG` and `@SQ` there is a tab ("\t"), while after `@CO` there is space (" ").
For samtools 1.9 this was not an issue. But, this changed for samtools 1.10.

**Comment by AlessioMilanese** [comment]
You have 2 possibilities for now to solve the issue:
1. Replace the file `mOTUs_v2/motus` with this: [motus.zip](https://github.com/motu-tool/mOTUs_v2/files/4769335/motus.zip). Note that you have to unzip it first.
2. remove samtools 1.10, and install samtools 1.9

I will solve the issue, test it and update the code next week.

**Comment by Shinexy99** [comment]
OK，I will try it

**Comment by AlessioMilanese** [comment]
Hi @Shinexy99,

Sorry I didn't see your answer. I was not notified that you edited the answer, I think I am notified only when there is a new message.

Try to run:
```
motus profile --test
```

If you get `Check resulting profile: correct`, then it's all good.
