### ISSUE TITLE
Identification down to strain level

### ISSUE THREAD

**Issue by termithorbor** [motu-tool/mOTUs_v2#53]
Hi all,

is it possible to identify different strains in metatranscriptomic data with this tool? Or is species the lowest taxonomic level?

Thanks for your answers :)

**Comment by AlessioMilanese** [comment]
Hi @termithorbor,
Thanks for your interest in mOTUs. 

> is it possible to identify different strains in metatranscriptomic data with this tool? Or is species the lowest taxonomic level?

mOTUs profiles only at species level.
