### ISSUE TITLE
misplaced sys.exit

### ISSUE THREAD

**Issue by hjruscheweyh** [motu-tool/mOTUs_v2#64]
As discussed. There is a random sys.exit in the the print_cami.py script. This doesnt affect the output but the command doesnt end with a 0.

https://github.com/motu-tool/mOTUs_v2/blob/9194f9b363aeb87473d8b4281baabe2f876a2d94/bin/print_CAMI.py#L408

**Comment by AlessioMilanese** [comment]
Solved in branch 2.6.1.
Will keep the issue open until we merge the branch.
