### ISSUE TITLE
[Feature request] conda installation without the dbs

### ISSUE THREAD

**Issue by matthpich** [motu-tool/mOTUs_v2#66]
Hi,

Thanks for the amazing tool.

Would it be feasible to install motusv2 via conda without the databases?
This could help save download time when testing the creation of conda environments on the fly, such as with [nextflow](https://www.nextflow.io/docs/latest/conda.html#use-conda-package-names).

And a related question, would it be possible to have a parameter to pass a custom database location?

Many thanks for your time considering this request!

**Comment by AlessioMilanese** [comment]
Hi @matthpich 

Thanks for your interest in mOTUs!

>Would it be feasible to install motusv2 via conda without the databases?
This could help save download time when testing the creation of conda environments on the fly, such as with nextflow.

That's a good point, but for how conda is handling the database it's not really possible to install it without the database. Also, for how mOTUs is designed, the database is an integral part of the tool.

> And a related question, would it be possible to have a parameter to pass a custom database location?

Ye check out the `-db` option when using `motus profile`.

**Comment by pichauma** [comment]
Alright @AlessioMilanese.
Many thanks for your prompt answer.
I will look for another workaround.

**Comment by matthpich** [comment]
Alright @AlessioMilanese.
Many thanks for your prompt answer.
I will look for another workaround.
